import {deflateSync} from 'node:zlib';
import {mkdirSync,writeFileSync} from 'node:fs';
import {performance} from 'node:perf_hooks';
import {World} from '../src/sim/world';
import {Mat} from '../src/sim/materials';
import {generateTerrain,regionAt,spawnPoint,surfaceAt} from '../src/sim/terrain';
import {liquidBasin,reachablePlayer} from '../src/sim/terrain-access';

const width=1024,height=1536,seeds=Array.from({length:30},(_,n)=>[0,1,7,91207,2147483647,2147483648,4294967295][n]??Math.imul(n,2654435761)>>>0);
const diagnosticSeeds=new Set([0,1,7,91207,4294967295]),out='.local/terrain',images='docs/images/terrain';mkdirSync(out,{recursive:true});mkdirSync(images,{recursive:true});

function components(world:World){const seen=new Uint8Array(world.cells.length),queue=new Int32Array(world.cells.length),sizes:number[]=[];for(let start=0;start<seen.length;start++){if(seen[start]||world.consolidated[start]||![Mat.Air,Mat.Water].includes(world.cells[start]))continue;let head=0,end=0;seen[start]=1;queue[end++]=start;while(head<end){const i=queue[head++],x=i%world.width;for(const j of [x?i-1:-1,x<world.width-1?i+1:-1,i>=world.width?i-world.width:-1,i<world.cells.length-world.width?i+world.width:-1])if(j>=0&&!seen[j]&&!world.consolidated[j]&&[Mat.Air,Mat.Water].includes(world.cells[j])){seen[j]=1;queue[end++]=j;}}sizes.push(end);}return sizes.sort((a,b)=>b-a);}
function bytes(world:World){let total=0;for(const value of Object.values(world))if(ArrayBuffer.isView(value))total+=value.byteLength;return total;}

const crcTable=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
function crc(data:Buffer){let c=0xffffffff;for(const b of data)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
function chunk(name:string,data:Buffer){const type=Buffer.from(name),body=Buffer.concat([type,data]),result=Buffer.alloc(data.length+12);result.writeUInt32BE(data.length,0);body.copy(result,4);result.writeUInt32BE(crc(body),data.length+8);return result;}
function png(path:string,w:number,h:number,pixel:(x:number,y:number)=>[number,number,number]){const raw=Buffer.alloc((w*3+1)*h);for(let y=0;y<h;y++){const row=y*(w*3+1);for(let x=0;x<w;x++){const color=pixel(x,y),i=row+1+x*3;raw[i]=color[0];raw[i+1]=color[1];raw[i+2]=color[2];}}const header=Buffer.alloc(13);header.writeUInt32BE(w,0);header.writeUInt32BE(h,4);header[8]=8;header[9]=2;writeFileSync(path,Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',deflateSync(raw,{level:9})),chunk('IEND',Buffer.alloc(0))]));}
function diagnostics(world:World,seed:number){const scale=2,w=world.width/scale,h=world.height/scale,data=world.generation!,roomPixels=new Set(data.rooms.map(r=>`${Math.floor(r.x/scale)},${Math.floor(r.y/scale)}`)),tunnelPixels=new Set(data.tunnels.flatMap(t=>t.points.map(p=>`${Math.floor(p.x/scale)},${Math.floor(p.y/scale)}`))),reservoir=(i:number)=>data.reservoirs.some(r=>{const x=i%world.width,y=Math.floor(i/world.width);return x>=r.bounds.left&&x<=r.bounds.right&&y>=r.bounds.top&&y<=r.bounds.bottom;});const regionColors=[[189,145,77],[121,88,61],[50,122,186],[122,163,190],[188,91,46],[102,72,123]],resourceColors:Record<number,[number,number,number]>={[Mat.Quartz]:[225,225,217],[Mat.Crystal]:[170,102,220],[Mat.Residue]:[180,94,52],[Mat.Ice]:[134,204,230]};
  const sample=(x:number,y:number)=>world.index(Math.min(world.width-1,x*scale),Math.min(world.height-1,y*scale));
  png(`${images}/seed-${seed}-binario.png`,w,h,(x,y)=>{const i=sample(x,y);return world.consolidated[i]?[37,40,43]:world.cells[i]===Mat.Water?[50,122,186]:[224,219,202];});
  png(`${images}/seed-${seed}-biomas.png`,w,h,(x,y)=>{const i=sample(x,y),r=regionAt(world,x*scale,y*scale),c=regionColors[r];return world.consolidated[i]?[Math.floor(c[0]*.28),Math.floor(c[1]*.28),Math.floor(c[2]*.28)]:c;});
  png(`${images}/seed-${seed}-salas.png`,w,h,(x,y)=>roomPixels.has(`${x},${y}`)?[243,207,76]:(world.consolidated[sample(x,y)]?[23,25,29]:[90,94,97]));
  png(`${images}/seed-${seed}-conexoes.png`,w,h,(x,y)=>tunnelPixels.has(`${x},${y}`)?[214,155,50]:(world.consolidated[sample(x,y)]?[23,25,29]:[67,73,78]));
  png(`${images}/seed-${seed}-recursos.png`,w,h,(x,y)=>resourceColors[world.cells[sample(x,y)]]??(world.consolidated[sample(x,y)]?[37,40,43]:[23,25,29]));
  png(`${images}/seed-${seed}-reservatorios.png`,w,h,(x,y)=>{const i=sample(x,y);return world.cells[i]===Mat.Water?[50,122,186]:reservoir(i)?[32,67,96]:(world.consolidated[i]?[37,40,43]:[23,25,29]);});
}

const results=[];for(const seed of seeds){const world=new World(width,height,seed),start=performance.now();generateTerrain(world);const generationMs=performance.now()-start,data=world.generation!,spawn=spawnPoint(world),access=reachablePlayer(world,spawn.x,spawn.y),empty=Array(6).fill(0),total=Array(6).fill(0),bins=Array(20).fill(0);for(let y=0;y<height;y++)for(let x=0;x<width;x++)if(y>=surfaceAt(world,x)){const r=regionAt(world,x,y),i=world.index(x,y);total[r]++;if(!world.consolidated[i]&&[Mat.Air,Mat.Water].includes(world.cells[i]))empty[r]++;}for(const room of data.rooms.filter(r=>!r.isolated)){const sx=Math.min(3,Math.floor(room.x/width*4)),sy=Math.min(4,Math.max(0,Math.floor((room.y-surfaceAt(world,room.x))/(height-surfaceAt(world,room.x))*5)));bins[sy*4+sx]++;}const basins=data.reservoirs.filter(r=>r.kind!=='drain').map(r=>{let sample=-1;for(let y=r.bounds.top;y<=r.bounds.bottom&&sample<0;y++)for(let x=r.bounds.left;x<=r.bounds.right;x++)if(world.cells[world.index(x,y)]===Mat.Water){sample=world.index(x,y);break;}return {kind:r.kind,count:r.count,contained:sample>=0&&Boolean(liquidBasin(world,sample%width,Math.floor(sample/width),r.level,r.count*2+100))};}),componentSizes=components(world),objectiveAccess=data.chambers.map(c=>({id:c.id,reachable:Boolean(access.reachable[world.index(c.x-20,c.y-4)])})),record={seed,generationMs,rooms:data.rooms.length,mainRooms:data.rooms.filter(r=>!r.isolated).length,tunnels:data.tunnels.length,extraTunnels:data.tunnels.filter(t=>t.extra).length,emptyFraction:empty.map((n,i)=>n/total[i]),spatialBins:bins,occupiedBins:bins.filter(Boolean).length,components:componentSizes.length,largestComponents:componentSizes.slice(0,8),playerReachableCells:access.count,objectiveAccess,reservoirs:basins,starter:{sand:world.count(Mat.Sand),water:world.count(Mat.Water)},typedArrayBytes:bytes(world),metadataBytes:Buffer.byteLength(JSON.stringify(data))};results.push(record);if(diagnosticSeeds.has(seed))diagnostics(world,seed);console.log(JSON.stringify(record));}
const report={generatedAt:new Date().toISOString(),dimensions:[width,height],acceptance:{seeds:30,minimumOccupiedBins:18,maximumRoomsPerBin:10,subterraneanRegionalEmptyFraction:[.17,.55],allMainRoomsPlayerAccessible:true,allObjectivesAccessible:true,allNaturalBasinsContained:true,maximumGenerationMs:1500},summary:{generationMs:{min:Math.min(...results.map(r=>r.generationMs)),mean:results.reduce((s,r)=>s+r.generationMs,0)/results.length,max:Math.max(...results.map(r=>r.generationMs))},rooms:{min:Math.min(...results.map(r=>r.rooms)),max:Math.max(...results.map(r=>r.rooms))},components:{min:Math.min(...results.map(r=>r.components)),max:Math.max(...results.map(r=>r.components))},typedArrayMiB:results[0].typedArrayBytes/1024**2,metadataKiB:{min:Math.min(...results.map(r=>r.metadataBytes))/1024,max:Math.max(...results.map(r=>r.metadataBytes))/1024}},results};writeFileSync(`${out}/report.json`,JSON.stringify(report,null,2));console.log('Relatório: '+out+'/report.json');
